version: '3.9'

services:
  server:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"